# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\bigKeeperPyUi_newLayout_v117.ui',
# licensing of '.\bigKeeperPyUi_newLayout_v117.ui' applies.
#
# Created: Wed Jun 30 13:02:46 2021
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 829)
        MainWindow.setMinimumSize(QtCore.QSize(400, 829))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_openCal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openCal.setObjectName("pushButton_openCal")
        self.horizontalLayout_9.addWidget(self.pushButton_openCal)
        self.pushButton_openCal2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openCal2.setObjectName("pushButton_openCal2")
        self.horizontalLayout_9.addWidget(self.pushButton_openCal2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_8 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setObjectName("label_8")
        self.comboBoxProjects = QtWidgets.QComboBox(self.splitter)
        self.comboBoxProjects.setObjectName("comboBoxProjects")
        self.verticalLayout.addWidget(self.splitter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../../../bigKeeper/bigKeeperIcon.jpg"))
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_currentOpen = QtWidgets.QWidget()
        self.tab_currentOpen.setObjectName("tab_currentOpen")
        self.pushButton_versionUp = QtWidgets.QPushButton(self.tab_currentOpen)
        self.pushButton_versionUp.setGeometry(QtCore.QRect(0, 100, 171, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.pushButton_versionUp.setFont(font)
        self.pushButton_versionUp.setObjectName("pushButton_versionUp")
        self.pushButton_revive = QtWidgets.QPushButton(self.tab_currentOpen)
        self.pushButton_revive.setGeometry(QtCore.QRect(0, 160, 71, 23))
        self.pushButton_revive.setObjectName("pushButton_revive")
        self.pushButton_getFrameRange = QtWidgets.QPushButton(self.tab_currentOpen)
        self.pushButton_getFrameRange.setGeometry(QtCore.QRect(0, 190, 171, 41))
        self.pushButton_getFrameRange.setObjectName("pushButton_getFrameRange")
        self.pushButton_NukeReadNodeTempTool = QtWidgets.QPushButton(self.tab_currentOpen)
        self.pushButton_NukeReadNodeTempTool.setGeometry(QtCore.QRect(0, 240, 171, 41))
        self.pushButton_NukeReadNodeTempTool.setObjectName("pushButton_NukeReadNodeTempTool")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_currentOpen)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 290, 411, 311))
        font = QtGui.QFont()
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabMaya = QtWidgets.QWidget()
        self.tabMaya.setObjectName("tabMaya")
        self.tabWidget_2.addTab(self.tabMaya, "")
        self.tabNuke = QtWidgets.QWidget()
        self.tabNuke.setObjectName("tabNuke")
        self.pushButton_closeNukeScript = QtWidgets.QPushButton(self.tabNuke)
        self.pushButton_closeNukeScript.setGeometry(QtCore.QRect(0, 250, 121, 23))
        self.pushButton_closeNukeScript.setObjectName("pushButton_closeNukeScript")
        self.pushButton_genWriteCompMaster = QtWidgets.QPushButton(self.tabNuke)
        self.pushButton_genWriteCompMaster.setGeometry(QtCore.QRect(0, 150, 121, 23))
        self.pushButton_genWriteCompMaster.setObjectName("pushButton_genWriteCompMaster")
        self.pushButton_genWriteLayerMask = QtWidgets.QPushButton(self.tabNuke)
        self.pushButton_genWriteLayerMask.setGeometry(QtCore.QRect(0, 170, 121, 23))
        self.pushButton_genWriteLayerMask.setObjectName("pushButton_genWriteLayerMask")
        self.label_16 = QtWidgets.QLabel(self.tabNuke)
        self.label_16.setGeometry(QtCore.QRect(0, 130, 121, 16))
        self.label_16.setObjectName("label_16")
        self.tabWidget_2.addTab(self.tabNuke, "")
        self.tabHoudini = QtWidgets.QWidget()
        self.tabHoudini.setObjectName("tabHoudini")
        self.tabWidget_2.addTab(self.tabHoudini, "")
        self.tabBlender = QtWidgets.QWidget()
        self.tabBlender.setObjectName("tabBlender")
        self.tabWidget_2.addTab(self.tabBlender, "")
        self.tabCmd = QtWidgets.QWidget()
        self.tabCmd.setObjectName("tabCmd")
        self.pushButton_sortoutfile = QtWidgets.QPushButton(self.tabCmd)
        self.pushButton_sortoutfile.setGeometry(QtCore.QRect(200, 30, 75, 23))
        self.pushButton_sortoutfile.setObjectName("pushButton_sortoutfile")
        self.label_17 = QtWidgets.QLabel(self.tabCmd)
        self.label_17.setGeometry(QtCore.QRect(0, 10, 151, 16))
        self.label_17.setTextFormat(QtCore.Qt.PlainText)
        self.label_17.setObjectName("label_17")
        self.pushButton_exeDel = QtWidgets.QPushButton(self.tabCmd)
        self.pushButton_exeDel.setGeometry(QtCore.QRect(370, 30, 31, 23))
        self.pushButton_exeDel.setObjectName("pushButton_exeDel")
        self.label_18 = QtWidgets.QLabel(self.tabCmd)
        self.label_18.setGeometry(QtCore.QRect(0, 30, 211, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tabCmd)
        self.label_19.setGeometry(QtCore.QRect(300, 30, 71, 16))
        self.label_19.setObjectName("label_19")
        self.tabWidget_2.addTab(self.tabCmd, "")
        self.tabLauncher = QtWidgets.QWidget()
        self.tabLauncher.setObjectName("tabLauncher")
        self.groupBox = QtWidgets.QGroupBox(self.tabLauncher)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 331, 251))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_LaunchNuke13_0_v2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_LaunchNuke13_0_v2.setGeometry(QtCore.QRect(50, 70, 61, 41))
        self.pushButton_LaunchNuke13_0_v2.setObjectName("pushButton_LaunchNuke13_0_v2")
        self.pushButton_LaunchNukeStudio13_0_v2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_LaunchNukeStudio13_0_v2.setGeometry(QtCore.QRect(190, 70, 41, 41))
        self.pushButton_LaunchNukeStudio13_0_v2.setObjectName("pushButton_LaunchNukeStudio13_0_v2")
        self.pushButton_LaunchNukeX13_0_v2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_LaunchNukeX13_0_v2.setGeometry(QtCore.QRect(110, 70, 41, 41))
        self.pushButton_LaunchNukeX13_0_v2.setObjectName("pushButton_LaunchNukeX13_0_v2")
        self.pushButton_LaunchNukeAssist13_0_v2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_LaunchNukeAssist13_0_v2.setGeometry(QtCore.QRect(150, 70, 41, 41))
        self.pushButton_LaunchNukeAssist13_0_v2.setObjectName("pushButton_LaunchNukeAssist13_0_v2")
        self.pushButton_LaunchMaya2022_update0 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_LaunchMaya2022_update0.setGeometry(QtCore.QRect(50, 30, 181, 41))
        self.pushButton_LaunchMaya2022_update0.setObjectName("pushButton_LaunchMaya2022_update0")
        self.pushButton_mayaOther = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_mayaOther.setGeometry(QtCore.QRect(230, 30, 16, 41))
        self.pushButton_mayaOther.setObjectName("pushButton_mayaOther")
        self.pushButton_nukeOther = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_nukeOther.setGeometry(QtCore.QRect(230, 70, 16, 41))
        self.pushButton_nukeOther.setObjectName("pushButton_nukeOther")
        self.label_mayaIcon = QtWidgets.QLabel(self.groupBox)
        self.label_mayaIcon.setGeometry(QtCore.QRect(10, 30, 41, 41))
        self.label_mayaIcon.setObjectName("label_mayaIcon")
        self.label_nukeIcon = QtWidgets.QLabel(self.groupBox)
        self.label_nukeIcon.setGeometry(QtCore.QRect(10, 70, 41, 41))
        self.label_nukeIcon.setObjectName("label_nukeIcon")
        self.tabWidget_2.addTab(self.tabLauncher, "")
        self.pushButton_scnUpdate = QtWidgets.QPushButton(self.tab_currentOpen)
        self.pushButton_scnUpdate.setGeometry(QtCore.QRect(80, 160, 91, 23))
        self.pushButton_scnUpdate.setObjectName("pushButton_scnUpdate")
        self.tabWidget.addTab(self.tab_currentOpen, "")
        self.tab_shotBrowser = QtWidgets.QWidget()
        self.tab_shotBrowser.setObjectName("tab_shotBrowser")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_shotBrowser)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.tab_shotBrowser)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_shotBrowser)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.listWidget_1 = QtWidgets.QListWidget(self.tab_shotBrowser)
        self.listWidget_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_1.setObjectName("listWidget_1")
        self.verticalLayout_2.addWidget(self.listWidget_1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab_shotBrowser)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_shotBrowser)
        self.listWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.listWidget_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_shotBrowser)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.pushButton_CompLatestRv = QtWidgets.QPushButton(self.tab_shotBrowser)
        self.pushButton_CompLatestRv.setObjectName("pushButton_CompLatestRv")
        self.verticalLayout_4.addWidget(self.pushButton_CompLatestRv)
        self.pushButton_shotAction = QtWidgets.QPushButton(self.tab_shotBrowser)
        self.pushButton_shotAction.setObjectName("pushButton_shotAction")
        self.verticalLayout_4.addWidget(self.pushButton_shotAction)
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_shotBrowser)
        self.listWidget_3.setMinimumSize(QtCore.QSize(0, 200))
        self.listWidget_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_4.addWidget(self.listWidget_3)
        self.pushButton_newTask = QtWidgets.QPushButton(self.tab_shotBrowser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_newTask.sizePolicy().hasHeightForWidth())
        self.pushButton_newTask.setSizePolicy(sizePolicy)
        self.pushButton_newTask.setObjectName("pushButton_newTask")
        self.verticalLayout_4.addWidget(self.pushButton_newTask)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_Location = QtWidgets.QLineEdit(self.tab_shotBrowser)
        self.lineEdit_Location.setObjectName("lineEdit_Location")
        self.horizontalLayout_4.addWidget(self.lineEdit_Location)
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_shotBrowser)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_4.addWidget(self.pushButton_19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_shotBrowser, "")
        self.tab_developing = QtWidgets.QWidget()
        self.tab_developing.setObjectName("tab_developing")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_developing)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 160, 320, 112))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_num9 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num9.setObjectName("pushButton_num9")
        self.gridLayout.addWidget(self.pushButton_num9, 0, 0, 1, 1)
        self.pushButton_num8 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num8.setObjectName("pushButton_num8")
        self.gridLayout.addWidget(self.pushButton_num8, 0, 1, 1, 1)
        self.pushButton_num7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num7.setObjectName("pushButton_num7")
        self.gridLayout.addWidget(self.pushButton_num7, 0, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 0, 3, 1, 1)
        self.pushButton_num6 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num6.setObjectName("pushButton_num6")
        self.gridLayout.addWidget(self.pushButton_num6, 1, 0, 1, 1)
        self.pushButton_num5 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num5.setObjectName("pushButton_num5")
        self.gridLayout.addWidget(self.pushButton_num5, 1, 1, 1, 1)
        self.pushButton_num4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num4.setObjectName("pushButton_num4")
        self.gridLayout.addWidget(self.pushButton_num4, 1, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 1, 3, 1, 1)
        self.pushButton_num3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num3.setObjectName("pushButton_num3")
        self.gridLayout.addWidget(self.pushButton_num3, 2, 0, 1, 1)
        self.pushButton_num2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num2.setObjectName("pushButton_num2")
        self.gridLayout.addWidget(self.pushButton_num2, 2, 1, 1, 1)
        self.pushButton_num1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_num1.setObjectName("pushButton_num1")
        self.gridLayout.addWidget(self.pushButton_num1, 2, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 3, 1, 1)
        self.pushButton_calculate = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.gridLayout.addWidget(self.pushButton_calculate, 3, 0, 1, 3)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 3, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_developing)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 290, 158, 77))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 1, 1, 2)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 2, 0, 1, 2)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_developing)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 20, 251, 25))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget_4)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_childUi = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_childUi.setObjectName("pushButton_childUi")
        self.horizontalLayout.addWidget(self.pushButton_childUi)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_developing)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 60, 251, 72))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_action1 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_action1.setObjectName("pushButton_action1")
        self.horizontalLayout_2.addWidget(self.pushButton_action1)
        self.pushButton_7zip = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_7zip.setObjectName("pushButton_7zip")
        self.horizontalLayout_2.addWidget(self.pushButton_7zip)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.tab_developing)
        self.toolButton.setGeometry(QtCore.QRect(190, 290, 151, 19))
        self.toolButton.setObjectName("toolButton")
        self.pushButton_Location_2 = QtWidgets.QPushButton(self.tab_developing)
        self.pushButton_Location_2.setGeometry(QtCore.QRect(350, 480, 61, 23))
        self.pushButton_Location_2.setObjectName("pushButton_Location_2")
        self.lineEdit_Location_2 = QtWidgets.QLineEdit(self.tab_developing)
        self.lineEdit_Location_2.setGeometry(QtCore.QRect(20, 480, 321, 20))
        self.lineEdit_Location_2.setObjectName("lineEdit_Location_2")
        self.label_10 = QtWidgets.QLabel(self.tab_developing)
        self.label_10.setGeometry(QtCore.QRect(20, 460, 321, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_overrideFrameRange = QtWidgets.QPushButton(self.tab_developing)
        self.pushButton_overrideFrameRange.setGeometry(QtCore.QRect(190, 380, 151, 23))
        self.pushButton_overrideFrameRange.setObjectName("pushButton_overrideFrameRange")
        self.toolButton_shotAction = QtWidgets.QToolButton(self.tab_developing)
        self.toolButton_shotAction.setGeometry(QtCore.QRect(190, 360, 123, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_shotAction.sizePolicy().hasHeightForWidth())
        self.toolButton_shotAction.setSizePolicy(sizePolicy)
        self.toolButton_shotAction.setObjectName("toolButton_shotAction")
        self.tabWidget.addTab(self.tab_developing, "")
        self.tab_assetBrowser = QtWidgets.QWidget()
        self.tab_assetBrowser.setObjectName("tab_assetBrowser")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_assetBrowser)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.tab_assetBrowser)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.tab_assetBrowser)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.listWidget_assetType = QtWidgets.QListWidget(self.tab_assetBrowser)
        self.listWidget_assetType.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_assetType.setObjectName("listWidget_assetType")
        self.verticalLayout_7.addWidget(self.listWidget_assetType)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.tab_assetBrowser)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.listWidget_asset = QtWidgets.QListWidget(self.tab_assetBrowser)
        self.listWidget_asset.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_asset.setObjectName("listWidget_asset")
        self.verticalLayout_8.addWidget(self.listWidget_asset)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.tab_assetBrowser)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.listWidget_assetTask = QtWidgets.QListWidget(self.tab_assetBrowser)
        self.listWidget_assetTask.setMinimumSize(QtCore.QSize(0, 200))
        self.listWidget_assetTask.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_assetTask.setObjectName("listWidget_assetTask")
        self.verticalLayout_9.addWidget(self.listWidget_assetTask)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_Location_3 = QtWidgets.QLineEdit(self.tab_assetBrowser)
        self.lineEdit_Location_3.setObjectName("lineEdit_Location_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_Location_3)
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_assetBrowser)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_7.addWidget(self.pushButton_20)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_assetBrowser, "")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pushButton_openCal.setText(QtWidgets.QApplication.translate("MainWindow", "Open bpvfx Calendar", None, -1))
        self.pushButton_openCal2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_openCal2", None, -1))
        self.pushButton_openCal2.setText(QtWidgets.QApplication.translate("MainWindow", "Open bpvfx Calendar", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Project Name :", None, -1))
        self.comboBoxProjects.setToolTip(QtWidgets.QApplication.translate("MainWindow", "comboBoxProjects", None, -1))
        self.pushButton_versionUp.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_versionUp", None, -1))
        self.pushButton_versionUp.setText(QtWidgets.QApplication.translate("MainWindow", "Version Up (Save WIP) ...", None, -1))
        self.pushButton_revive.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_revive", None, -1))
        self.pushButton_revive.setText(QtWidgets.QApplication.translate("MainWindow", "Revive...", None, -1))
        self.pushButton_getFrameRange.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_getFrameRange", None, -1))
        self.pushButton_getFrameRange.setText(QtWidgets.QApplication.translate("MainWindow", "Get Frame Range\n"
"- output setting -", None, -1))
        self.pushButton_NukeReadNodeTempTool.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_NukeReadNodeTempTool", None, -1))
        self.pushButton_NukeReadNodeTempTool.setText(QtWidgets.QApplication.translate("MainWindow", "Get Frame Range\n"
"- Nuke Read Nodes -", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabMaya), QtWidgets.QApplication.translate("MainWindow", "Maya", None, -1))
        self.pushButton_closeNukeScript.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_closeNukeScript", None, -1))
        self.pushButton_closeNukeScript.setText(QtWidgets.QApplication.translate("MainWindow", "close Nuke Script", None, -1))
        self.pushButton_genWriteCompMaster.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_genWriteCompMaster", None, -1))
        self.pushButton_genWriteCompMaster.setText(QtWidgets.QApplication.translate("MainWindow", "CompMaster (only 1)", None, -1))
        self.pushButton_genWriteLayerMask.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_genWriteLayerMask", None, -1))
        self.pushButton_genWriteLayerMask.setText(QtWidgets.QApplication.translate("MainWindow", "LayerMasks", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Gen Write Node :", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabNuke), QtWidgets.QApplication.translate("MainWindow", "Nuke", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabHoudini), QtWidgets.QApplication.translate("MainWindow", "Houdini", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabBlender), QtWidgets.QApplication.translate("MainWindow", "Blender", None, -1))
        self.pushButton_sortoutfile.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_sortoutfile", None, -1))
        self.pushButton_sortoutfile.setText(QtWidgets.QApplication.translate("MainWindow", "Sort Out", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Clean Up Comp Versions:", None, -1))
        self.pushButton_exeDel.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_sortoutfile", None, -1))
        self.pushButton_exeDel.setText(QtWidgets.QApplication.translate("MainWindow", "Del", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "1) Sort Out by Keeping Versions & Days :", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "2) Execut Del", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabCmd), QtWidgets.QApplication.translate("MainWindow", "Cmd", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Studio Dedicated Launcher:", None, -1))
        self.pushButton_LaunchNuke13_0_v2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_LaunchNuke13_0_v2", None, -1))
        self.pushButton_LaunchNuke13_0_v2.setText(QtWidgets.QApplication.translate("MainWindow", "Nuke\n"
"13.0v2", None, -1))
        self.pushButton_LaunchNukeStudio13_0_v2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_LaunchNukeStudio13_0_v2", None, -1))
        self.pushButton_LaunchNukeStudio13_0_v2.setText(QtWidgets.QApplication.translate("MainWindow", "studio", None, -1))
        self.pushButton_LaunchNukeX13_0_v2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_LaunchNukeX13_0_v2", None, -1))
        self.pushButton_LaunchNukeX13_0_v2.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.pushButton_LaunchNukeAssist13_0_v2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_LaunchNukeAssist13_0_v2", None, -1))
        self.pushButton_LaunchNukeAssist13_0_v2.setText(QtWidgets.QApplication.translate("MainWindow", "assist", None, -1))
        self.pushButton_LaunchMaya2022_update0.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_LaunchMaya2022_update0", None, -1))
        self.pushButton_LaunchMaya2022_update0.setText(QtWidgets.QApplication.translate("MainWindow", "Maya 2022 update0", None, -1))
        self.pushButton_mayaOther.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_mayaOther", None, -1))
        self.pushButton_mayaOther.setText(QtWidgets.QApplication.translate("MainWindow", ">", None, -1))
        self.pushButton_nukeOther.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_nukeOther", None, -1))
        self.pushButton_nukeOther.setText(QtWidgets.QApplication.translate("MainWindow", ">", None, -1))
        self.label_mayaIcon.setToolTip(QtWidgets.QApplication.translate("MainWindow", "label_mayaIcon", None, -1))
        self.label_mayaIcon.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_nukeIcon.setToolTip(QtWidgets.QApplication.translate("MainWindow", "label_nukeIcon", None, -1))
        self.label_nukeIcon.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabLauncher), QtWidgets.QApplication.translate("MainWindow", "Launcher", None, -1))
        self.pushButton_scnUpdate.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_scnUpdate", None, -1))
        self.pushButton_scnUpdate.setText(QtWidgets.QApplication.translate("MainWindow", "Scene Update", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_currentOpen), QtWidgets.QApplication.translate("MainWindow", "Currently Open", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "SHOT BROWSER", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Sequence", None, -1))
        self.listWidget_1.setToolTip(QtWidgets.QApplication.translate("MainWindow", "listWidget_1", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Shot", None, -1))
        self.listWidget_2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "listWidget_2", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Task Shot", None, -1))
        self.pushButton_CompLatestRv.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_CompLatestRv", None, -1))
        self.pushButton_CompLatestRv.setText(QtWidgets.QApplication.translate("MainWindow", "tmp.RvCompLastVer", None, -1))
        self.pushButton_shotAction.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_shotAction", None, -1))
        self.pushButton_shotAction.setText(QtWidgets.QApplication.translate("MainWindow", "Action...", None, -1))
        self.listWidget_3.setToolTip(QtWidgets.QApplication.translate("MainWindow", "listWidget_3", None, -1))
        self.pushButton_newTask.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_newTask", None, -1))
        self.pushButton_newTask.setText(QtWidgets.QApplication.translate("MainWindow", "New Task", None, -1))
        self.lineEdit_Location.setToolTip(QtWidgets.QApplication.translate("MainWindow", "lineEdit_Location", None, -1))
        self.pushButton_19.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_19", None, -1))
        self.pushButton_19.setText(QtWidgets.QApplication.translate("MainWindow", "explore...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_shotBrowser), QtWidgets.QApplication.translate("MainWindow", "Shot Browser", None, -1))
        self.pushButton_num9.setText(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.pushButton_num8.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.pushButton_num7.setText(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.pushButton_13.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.pushButton_num6.setText(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.pushButton_num5.setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.pushButton_num4.setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.pushButton_14.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.pushButton_num3.setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.pushButton_num2.setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.pushButton_num1.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.pushButton_15.setText(QtWidgets.QApplication.translate("MainWindow", "*", None, -1))
        self.pushButton_calculate.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.pushButton_16.setText(QtWidgets.QApplication.translate("MainWindow", "/", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "ID", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "PW", None, -1))
        self.pushButton_17.setText(QtWidgets.QApplication.translate("MainWindow", "OK", None, -1))
        self.pushButton_18.setText(QtWidgets.QApplication.translate("MainWindow", "Cancel", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.pushButton_childUi.setText(QtWidgets.QApplication.translate("MainWindow", "Launch Child Ui", None, -1))
        self.pushButton_action1.setText(QtWidgets.QApplication.translate("MainWindow", "call a blender bat", None, -1))
        self.pushButton_7zip.setText(QtWidgets.QApplication.translate("MainWindow", "Launch 7-zip", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "ACTIONS ...", None, -1))
        self.pushButton_Location_2.setText(QtWidgets.QApplication.translate("MainWindow", "explore...", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Location of currently opened wip:", None, -1))
        self.pushButton_overrideFrameRange.setText(QtWidgets.QApplication.translate("MainWindow", "Override Frame Range", None, -1))
        self.toolButton_shotAction.setToolTip(QtWidgets.QApplication.translate("MainWindow", "toolButton_shotAction", None, -1))
        self.toolButton_shotAction.setText(QtWidgets.QApplication.translate("MainWindow", "ACTIONS ...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_developing), QtWidgets.QApplication.translate("MainWindow", "developing", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "ASSET BROWSER", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Asset Type", None, -1))
        self.listWidget_assetType.setToolTip(QtWidgets.QApplication.translate("MainWindow", "listWidget_assetType", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Asset", None, -1))
        self.listWidget_asset.setToolTip(QtWidgets.QApplication.translate("MainWindow", "listWidget_asset", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Asset Task", None, -1))
        self.listWidget_assetTask.setToolTip(QtWidgets.QApplication.translate("MainWindow", "listWidget_assetTask", None, -1))
        self.lineEdit_Location_3.setToolTip(QtWidgets.QApplication.translate("MainWindow", "lineEdit_Location_3", None, -1))
        self.pushButton_20.setToolTip(QtWidgets.QApplication.translate("MainWindow", "pushButton_20", None, -1))
        self.pushButton_20.setText(QtWidgets.QApplication.translate("MainWindow", "explore...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_assetBrowser), QtWidgets.QApplication.translate("MainWindow", "developing Browser", None, -1))

